Repository Potion-Studios/BYG, pull requests merged in 2023-10, with the labels that each got.

#1256 Added check to setting of state that it is the block that is expected
  Common/src/main/java/potionstudios/byg/common/blockentity/HypogealImperiumBlockEntity.java
Labels: Bug, 1.19

#1255 Added check to setting of state that it is the block that is expected
  Common/src/main/java/potionstudios/byg/common/blockentity/HypogealImperiumBlockEntity.java
Labels: Bug, 1.19, Backport

#1260 Patternable saplings of all kinds
  Common/src/main/java/potionstudios/byg/common/block/BYGFungusBlock.java
  Common/src/main/java/potionstudios/byg/common/block/BYGMushroomBlock.java
  Common/src/main/java/potionstudios/byg/common/block/sapling/BYGSaplingBlock.java
  Common/src/main/java/potionstudios/byg/common/block/sapling/GrowingPatterns.java
  Common/src/main/java/potionstudios/byg/mixin/common/block/SaplingBlockMixin.java
  Common/src/main/java/potionstudios/byg/util/FeatureGrowerFromBlockPattern.java
  Common/src/main/resources/byg.mixins.json
Labels: Enhancement

#1263 Patterns go brrrr
  Common/src/main/java/potionstudios/byg/common/block/BYGFungusBlock.java
  Common/src/main/java/potionstudios/byg/common/block/BYGMushroomBlock.java
  Common/src/main/java/potionstudios/byg/common/block/sapling/BYGSaplingBlock.java
  Common/src/main/java/potionstudios/byg/common/block/sapling/GrowingPatterns.java
  Common/src/main/java/potionstudios/byg/mixin/common/block/SaplingBlockMixin.java
  Common/src/main/java/potionstudios/byg/util/FeatureGrowerFromBlockPattern.java
  Common/src/main/resources/byg.mixins.json
Labels: Enhancement
